import time
import os
import json
import asyncio
from contextlib import asynccontextmanager
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional, AsyncGenerator

from backend.config import settings
from backend.graph import run_agentic_rag_pipeline, agent_pipeline_graph
from backend.agents import run_data_retriever_agent, run_report_generator_agent_astream
from backend.rag_tool import get_semantic_retriever

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("🚀 Pre-warming RAG Vector Store & Embedding Model...")
    get_semantic_retriever()
    print("✅ RAG Vector Store pre-warmed and ready!")
    yield

app = FastAPI(
    title="Agentic AI Report Generator Backend",
    description="FastAPI service exposing OpenAI-compatible API for LangGraph Agent Pipeline",
    version="1.0.0",
    lifespan=lifespan
)

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatCompletionRequest(BaseModel):
    model: Optional[str] = None
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.7
    stream: Optional[bool] = False

from backend.llm_factory import get_llm
from langchain_core.messages import HumanMessage

BASE_MODEL_NAME = "gpt-5-mini-base"

@app.get("/")
def read_root():
    return {
        "status": "online",
        "service": "Agentic AI Report Generator API",
        "display_model": settings.DISPLAY_MODEL_NAME,
        "base_model": BASE_MODEL_NAME,
        "target_model": settings.OPENAI_MODEL,
        "llm_provider": settings.LLM_PROVIDER,
        "base_url": settings.OPENAI_BASE_URL
    }

@app.get("/v1/models")
def list_models():
    """
    OpenAI-compatible models list endpoint for Open WebUI discovery.
    Exposes both RAG Agentic System and Pure Base LLM for side-by-side comparison.
    """
    now = int(time.time())
    display_id = settings.DISPLAY_MODEL_NAME
    return {
        "object": "list",
        "data": [
            {
                "id": display_id,
                "object": "model",
                "created": now,
                "owned_by": "bbl-agent-team",
                "permission": [],
                "root": display_id,
                "parent": None
            },
            {
                "id": BASE_MODEL_NAME,
                "object": "model",
                "created": now,
                "owned_by": "bbl-agent-team",
                "permission": [],
                "root": BASE_MODEL_NAME,
                "parent": None
            }
        ]
    }

async def generate_stream_base_response(user_query: str, request_model: str) -> AsyncGenerator[str, None]:
    """
    Streams responses directly from the underlying LLM (without Agent 1 RAG context retrieval).
    """
    chat_id = f"chatcmpl-{int(time.time())}"
    llm = get_llm()
    messages = [HumanMessage(content=user_query)]
    try:
        async for chunk in llm.astream(messages):
            if chunk.content:
                payload = {
                    "id": chat_id,
                    "object": "chat.completion.chunk",
                    "created": int(time.time()),
                    "model": request_model,
                    "choices": [
                        {
                            "index": 0,
                            "delta": {"content": chunk.content},
                            "finish_reason": None
                        }
                    ]
                }
                yield f"data: {json.dumps(payload)}\n\n"

        stop_payload = {
            "id": chat_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": request_model,
            "choices": [
                {
                    "index": 0,
                    "delta": {},
                    "finish_reason": "stop"
                }
            ]
        }
        yield f"data: {json.dumps(stop_payload)}\n\n"
        yield "data: [DONE]\n\n"
    except Exception as e:
        print(f"Error executing Base LLM response: {e}")
        error_payload = {
            "error": {"message": str(e), "type": "server_error"}
        }
        yield f"data: {json.dumps(error_payload)}\n\n"
        yield "data: [DONE]\n\n"

async def generate_stream_agent_response(user_query: str, request_model: str) -> AsyncGenerator[str, None]:
    """
    Executes Agent 1 (Retriever) and streams Agent 2 (Report Generator) tokens in real-time.
    """
    chat_id = f"chatcmpl-{int(time.time())}"
    
    try:
        # Step 1: Agent 1 retrieves relevant context snippets (~50ms)
        retrieved_snippets = run_data_retriever_agent(user_query)

        # Step 2: Agent 2 streams synthesized tokens in real-time as generated by LLM
        async for token in run_report_generator_agent_astream(user_query, retrieved_snippets):
            payload = {
                "id": chat_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": request_model,
                "choices": [
                    {
                        "index": 0,
                        "delta": {"content": token},
                        "finish_reason": None
                    }
                ]
            }
            yield f"data: {json.dumps(payload)}\n\n"

        # Step 3: Append collapsible source snippets if SHOW_RETRIEVED_SNIPPETS is enabled
        if settings.SHOW_RETRIEVED_SNIPPETS and retrieved_snippets:
            sources_block = f"\n\n---\n<details>\n<summary>🔍 View Retrieved Context Snippets (Agent 1 RAG Output)</summary>\n\n{retrieved_snippets}\n\n</details>\n"
            payload = {
                "id": chat_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": request_model,
                "choices": [
                    {
                        "index": 0,
                        "delta": {"content": sources_block},
                        "finish_reason": None
                    }
                ]
            }
            yield f"data: {json.dumps(payload)}\n\n"

        # Final stop payload
        stop_payload = {
            "id": chat_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": request_model,
            "choices": [
                {
                    "index": 0,
                    "delta": {},
                    "finish_reason": "stop"
                }
            ]
        }
        yield f"data: {json.dumps(stop_payload)}\n\n"
        yield "data: [DONE]\n\n"
    except Exception as e:
        print(f"Error executing LangGraph pipeline: {e}")
        error_payload = {
            "error": {"message": str(e), "type": "server_error"}
        }
        yield f"data: {json.dumps(error_payload)}\n\n"
        yield "data: [DONE]\n\n"

@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """
    OpenAI-compatible chat completions endpoint routing to either:
    1. AI_Report_Generator (LangGraph 2-Agent RAG Pipeline)
    2. gpt-5-mini-base (Direct LLM without RAG context)
    """
    user_query = ""
    for msg in reversed(request.messages):
        if msg.role == "user":
            user_query = msg.content
            break
            
    if not user_query:
        user_query = "Hello"

    request_model = request.model or settings.DISPLAY_MODEL_NAME

    # Route: Base LLM without RAG context
    if request_model == BASE_MODEL_NAME:
        if request.stream:
            return StreamingResponse(
                generate_stream_base_response(user_query, request_model),
                media_type="text/event-stream"
            )
        else:
            try:
                llm = get_llm()
                res = await llm.ainvoke([HumanMessage(content=user_query)])
                return {
                    "id": f"chatcmpl-{int(time.time())}",
                    "object": "chat.completion",
                    "created": int(time.time()),
                    "model": request_model,
                    "choices": [
                        {
                            "index": 0,
                            "message": {
                                "role": "assistant",
                                "content": res.content
                            },
                            "finish_reason": "stop"
                        }
                    ]
                }
            except Exception as e:
                raise HTTPException(status_code=500, detail=f"Base LLM Error: {str(e)}")

    # Route: Full LangGraph RAG Agent Pipeline
    if request.stream:
        return StreamingResponse(
            generate_stream_agent_response(user_query, request_model),
            media_type="text/event-stream"
        )

    # Non-streaming RAG Agent Pipeline
    try:
        final_report = run_agentic_rag_pipeline(user_query)
        return {
            "id": f"chatcmpl-{int(time.time())}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": request_model,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": final_report
                    },
                    "finish_reason": "stop"
                }
            ],
            "usage": {
                "prompt_tokens": 50,
                "completion_tokens": 200,
                "total_tokens": 250
            }
        }
    except Exception as e:
        print(f"Error executing LangGraph agent pipeline: {e}")
        raise HTTPException(status_code=500, detail=f"Agent Pipeline Error: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.main:app", host="0.0.0.0", port=8000, reload=True)
